apiVersion: v1
kind: Service
metadata:
  name: {{ include "drdavisicecream.fullname" . }}
spec:
  ports:
  - name: tcp-drdavisicec
    port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
  - name: http
    port: 80
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "drdavisicecream.fullname" . }}
